const express = require('express')
const connect = require('./src/db/connect')
const dotenv = require('dotenv')
const path = require('path')
const cookieParser = require('cookie-parser')

dotenv.config()

const app = express()
const PORT = process.env.PORT || 3000

//Configuration for data collections

app.use(express.json())
app.use(express.urlencoded({extended: false}))
app.use(cookieParser())

//Establishing databse connection
connect()

//Configuring views file for server-side-rendering
app.set("view engine", "ejs")
app.set("views", path.resolve("./src/views"))

//Importing routes 
const staticRouter = require('./src/routes/static/user.static.routes')
const urlRouter = require('./src/routes/url.routes')
const userRouter = require('./src/routes/user.routes')

//Importing middlewares
const restrictToLoggedInUser = require('./src/middlewares/restrictToLoggedInUserOnly.middleware')

//I Thik the project is stopped here because of sessionID. As of now, the map will get empty whenever server refreshed. It means
//the /url route is restricted because server can't able to find that particular logged in guy. So the whole /url path get blocked
//because of unsufficient task is handled by the map function which is in the middleware. This project will not starts untill i not
//find the solution of the problem. At the end, i'm removing the middleware so that the application works smoothly. 

//Limitation :: User can't see their own particular shortID which is generated by them.

//Configuring routes with handlers
app.use('/', staticRouter)
app.use('/url', urlRouter)
app.use('/user', userRouter)

app.listen(PORT, (err) => {
    if(err){
        console.error("Error while listening on PORT" + PORT)
    }else {
        console.log(`Server is listening on http://localhost:${PORT}`)
    }
})